name: "🔍 Review Issue"
description: "Submit a review request for code, features, or documents."
title: "[REVIEW] - <title>"
labels: ["review", "pending-review"]
body:
  - type: checkboxes
    id: review_type
    attributes:
      label: "📌 Review Type"
      description: "Select the type of review required."
      options:
        - label: "Code Review"
        - label: "Pull Request (PR) Review"
        - label: "Documentation Review"
        - label: "Meeting Notes Review"
    validations:
      required: true

  - type: textarea
    id: review_summary
    attributes:
      label: "📝 Review Summary"
      description: "Provide a brief summary of what needs to be reviewed."
      placeholder: "e.g., Reviewing the implementation of Feature XYZ."
    validations:
      required: true

  - type: textarea
    id: changes_made
    attributes:
      label: "🔄 Changes Made"
      description: "Describe the changes that need to be reviewed."
      placeholder: "List down key modifications or features implemented."
    validations:
      required: true

  - type: input
    id: related_topic
    attributes:
      label: "🔗 Related Topic"
      description: "Specify the related topic, feature, or pull request (if applicable)."
      placeholder: "e.g., Pull Request #42 or Feature XYZ"
    validations:
      required: false

  - type: textarea
    id: concerns
    attributes:
      label: "⚠️ Concerns"
      description: "Mention any specific concerns or areas that need extra attention."
      placeholder: "e.g., potential issues, alternative implementations."
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: "🗒️ Additional Notes"
      description: "Any extra context or details?"
      placeholder: "e.g., Dependencies, blockers, or next steps."
    validations:
      required: false
